version: "3.7"

services:
  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/algo_visualization_backend
      - ./nginx:/etc/nginx.conf.d
    depends_on:
      - algo_backend

  algo_backend:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: algo_visualization_backend

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/usr/src/algo_visualization_backend

    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn config.wsqi.application --bind 0.0.0.0:8000"