version: "3.7"

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: algo_visualization_backend

    restart: always

    ports:
      - 8000:8000

    env_file:
      - .env

    depends_on:
      - db

    volumes:
      - .:/usr/src/algo_visualization_backend

    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"